name: Deploy Dataproc WorkflowTemplate and Create a Schedule to run it

env:
    BRONZE_DATALAKE_FILES: bronze
    TRANSIENT_DATALAKE_FILES: transient
    BUCKET_DATALAKE_FOLDER: transient
    BUCKET_BIGDATA_JAR_FOLDER: jars
    BUCKET_BIGDATA_PYSPARK_FOLDER: scripts
    PYSPARK_INGESTION_SCRIPT : ingestion_csv_to_delta.py 
    REGION: us-east1
    ZONE: us-east1-b
    DATAPROC_CLUSTER_NAME : dataproc-bigdata-multi-node-cluster
    DATAPROC_WORKER_TYPE : n2-standard-2
    DATAPROC_MASTER_TYPE : n2-standard-2
    DATAPROC_NUM_WORKERS : 2
    DATAPROC_IMAGE_VERSION : 2.1-debian11
    DATAPROC_WORKER_NUM_LOCAL_SSD: 1
    DATAPROC_MASTER_NUM_LOCAL_SSD: 1
    DATAPROC_MASTER_BOOT_DISK_SIZE: 32   
    DATAPROC_WORKER_DISK_SIZE: 32
    DATAPROC_MASTER_BOOT_DISK_TYPE: pd-balanced
    DATAPROC_WORKER_BOOT_DISK_TYPE: pd-balanced
    DATAPROC_COMPONENTS: JUPYTER
    DATAPROC_WORKFLOW_NAME: departments_etl
    DATAPROC_WORKFLOW_INGESTION_STEP_NAME: ingestion_countries_csv_to_delta 
    JAR_LIB1 : delta-core_2.12-2.3.0.jar
    JAR_LIB2 : delta-storage-2.3.0.jar 
    APP_NAME : 'countries_ingestion_csv_to_delta'
    SUBJECT : departments
    STEP1 : countries
    STEP2 : departments
    STEP3 : employees
    TIME_ZONE : America/Sao_Paulo
    SCHEDULE : "20 12 * * *"
    SCHEDULE_NAME : schedule_departments_etl
    SERVICE_ACCOUNT_NAME : dataproc-workflow-run
    CUSTOM_ROLE : dataproc_workflow_custom_role




on:
    push:
        branchs: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Authorize GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json:  ${{ secrets.GCP_SA_KEY }}
    
    # Step to Authenticate with GCP
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 363.0.0'
        project_id: ${{ secrets.PROJECT_ID }}

    # Step to Configure Docker to use the gcloud command-line tool as a credential helper
    - name: Configure Docker
      run: |-
        gcloud auth configure-docker
#    - name: Add the custom role for service account
#      run: |-
#        gcloud projects add-iam-policy-binding ${secrets.PROJECT_ID} \
#        --member=serviceAccount:${env.SERVICE_ACCOUNT_NAME}@${secrets.PROJECT_ID}.iam.gserviceaccount.com \
#        --role=projects/${secrets.PROJECT_ID}/roles/${env.CUSTOM_ROLE}

    - name: Create cloud schedule for workflow execution
      run: |-
        gcloud scheduler jobs create http ${env.SCHEDULE_NAME} \
        --schedule="30 12 * * *" \
        --description="Dataproc workflow " \
        --location=${env.REGION}\
        --uri=https://dataproc.googleapis.com/v1/projects/${ secrets.PROJECT_ID}/regions/${ env.REGION}/workflowTemplates/${env.DATAPROC_WORKFLOW_NAME}:instantiate?alt=json \
        --time-zone=${env.TIME_ZONE} \
        --oauth-service-account-email=${env.SERVICE_ACCOUNT_NAME}@${secrets.PROJECT_ID}.iam.gserviceaccount.com

    
